services:
  # Elasticsearch service
  elasticsearch:
    image: elasticsearch:8.17.4
    container_name: deenji_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
      - '9300:9300'
    mem_limit: 1g
    networks:
      - external_supabase_network
      - deenji_network

  # Deenji AnalogJS application
  deenji-app:
    image: ghcr.io/${{ github.repository }}/deenji-app:latest # Use pre-built image
    container_name: deenji_app
    ports:
      - '8081:8081'
    env_file:
      - .env # Created by GitHub Actions with environment-specific values
    environment:
      # Override for Docker networking
      - NODE_ENV=production
      - NITRO_PORT=8081
      - NITRO_HOST=0.0.0.0
      - VITE_ELASTICSEARCH_URL=http://elasticsearch:9200 # Internal Docker network
    depends_on:
      - elasticsearch
    restart: unless-stopped
    networks:
      - external_supabase_network
      - deenji_network

volumes:
  es_data:
    name: deenji_elasticsearch_data

networks:
  external_supabase_network:
    external: true
    name: supabase_network_deenji-supabase
  deenji_network:
    name: deenji_internal_network
