services:
  elasticsearch:
    image: elasticsearch:8.17.4
    container_name: deenji_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Disable security for local dev (enable in prod)
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
      - '9300:9300'
    mem_limit: 1g
    networks:
      - external_supabase_network

volumes:
  es_data:
    name: deenji_elasticsearch_data

networks:
  external_supabase_network:
    external: true
    name: supabase_network_deenji-supabase
