name: Debug Secrets

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  debug:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Check if secrets exist
        run: |
          echo "=== Checking Secrets ==="
          echo "VPS_HOST exists: ${{ secrets.VPS_HOST != '' }}"
          echo "VPS_USER exists: ${{ secrets.VPS_USER != '' }}"
          echo "VPS_SSH_KEY exists: ${{ secrets.VPS_SSH_KEY != '' }}"
          echo "VPS_SSH_KEY starts with: ${{ startsWith(secrets.VPS_SSH_KEY, '-----BEGIN') }}"

          # Check length to ensure it's not empty
          echo "VPS_HOST length: ${{ secrets.VPS_HOST }}" | wc -c
          echo "VPS_USER value: ${{ secrets.VPS_USER }}"

      - name: Test with hardcoded username
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: github-deploy # Hardcode this
          key: ${{ secrets.VPS_SSH_KEY }}
          script: echo "If you see this, SSH worked!"
