name: Test SSH

on:
  workflow_dispatch: # Manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Connected successfully!"
            whoami
            pwd
