name: Deploy Deenji

on:
  push:
    branches:
      - main
      - production

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment: ${{ github.ref == 'refs/heads/production' && 'production' || 'staging' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/production" ]]; then
            echo "DEPLOY_ENV=production" >> $GITHUB_ENV
            echo "DEPLOY_HOST=${{ secrets.PROD_VPS_HOST || secrets.VPS_HOST }}" >> $GITHUB_ENV
            echo "APP_URL=https://yourdomain.com" >> $GITHUB_ENV
            echo "SUPABASE_URL=https://api.yourdomain.com" >> $GITHUB_ENV
          else
            echo "DEPLOY_ENV=staging" >> $GITHUB_ENV
            echo "DEPLOY_HOST=${{ secrets.VPS_HOST }}" >> $GITHUB_ENV
            echo "APP_URL=https://demo.dunup.ch" >> $GITHUB_ENV
            echo "SUPABASE_URL=http://localhost:54321" >> $GITHUB_ENV
          fi

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          # Pass secrets as environment variables to the SSH session
          envs: SUPABASE_ANON_KEY,DATABASE_URL,GOOGLE_API_KEY,DEPLOY_ENV,APP_URL,SUPABASE_URL
          script: |
            # Navigate to project directory
            cd ~/deenji-project

            # Stop Caddy if running (for port 8081)
            sudo systemctl stop caddy || true

            # Pull latest code from appropriate branch
            git pull origin main

            # Create .env file with actual secret values
            cat > .env << EOF
            # Environment configuration
            VITE_production=$([[ "$DEPLOY_ENV" == "production" ]] && echo "true" || echo "false")
            VITE_supabaseUrl=$SUPABASE_URL
            baseUrl=$APP_URL

            # Elasticsearch URL (will be overridden by docker-compose for internal network)
            VITE_ELASTICSEARCH_URL=http://localhost:9200

            # Secrets from GitHub Environment
            VITE_supabaseKey=$SUPABASE_ANON_KEY
            DATABASE_URL=$DATABASE_URL
            VITE_GOOGLE_API_KEY=$GOOGLE_API_KEY
            VITE_googleMapsApiKey=$GOOGLE_API_KEY
            VITE_GOOGLE_MAPS_API_KEY=$GOOGLE_API_KEY
            EOF

            # Show that env file was created (without showing secrets)
            echo "Created .env file with $(wc -l < .env) lines"

            # Stop existing containers
            docker compose down

            # Build with no cache for fresh build
            docker compose build --no-cache deenji-app

            # Start all services
            docker compose up -d

            # Wait for services to be healthy
            sleep 10

            # Check if services are running
            docker compose ps

            # Clean up old images
            docker image prune -f

            # Show logs for debugging
            echo "=== Recent logs ==="
            docker compose logs --tail=50 deenji-app
        env:
          # These environment variables will be available in the SSH session
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
