name: Test SSH Connection

on:
  workflow_dispatch: # Manual trigger only
  push:
    branches: [main] # Or trigger on push for testing

jobs:
  test:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Connected successfully!"
            whoami
            pwd
            ls -la

      - name: Show secrets status
        run: |
          echo "VPS_HOST is set: ${{ secrets.VPS_HOST != '' }}"
          echo "VPS_USER is set: ${{ secrets.VPS_USER != '' }}"
          echo "VPS_SSH_KEY is set: ${{ secrets.VPS_SSH_KEY != '' }}"
          echo "SUPABASE_ANON_KEY is set: ${{ secrets.SUPABASE_ANON_KEY != '' }}"
          echo "Environment: staging"
